# Generated by Django 4.1.13 on 2026-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_libraryitem_avatar_data_libraryitem_saved_at_playlist_playlistvideo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='libraryitem',
            new_name='core_librar_library_2f6b8d_idx',
            old_name='core_librar_library_saved_idx',
        ),
        migrations.AddField(
            model_name='deafuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
