# Generated by Django 4.1.13 on 2026-05-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deafuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='sync_sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='sync_sequence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
