# Generated by Django 4.1.13 on 2026-05-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conversion_sync_sequence_libraryitem_sync_sequence'),
        ('core', '0005_streamjob_streamchunk'),
    ]

    operations = [
    ]
