# Generated by Django 4.1.13 on 2026-05-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260513_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='sync_sequence',
        ),
        migrations.RemoveField(
            model_name='libraryitem',
            name='sync_sequence',
        ),
        migrations.AddField(
            model_name='streamchunk',
            name='animation_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamchunk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='streamjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
